# Generated by Django 5.2.15 on 2026-06-04 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('partner', 'Partner'), ('family', 'Family'), ('friend', 'Friend'), ('coworker', 'Coworker')], max_length=30)),
                ('occasion_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('monthsary', 'Monthsary'), ('graduation', 'Graduation'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('valentines', "Valentine's Day"), ('mothers_day', "Mother's Day"), ('fathers_day', "Father's Day"), ('family_reunion', 'Family Reunion'), ('wedding', 'Wedding'), ('baby_shower', 'Baby Shower'), ('promotion', 'Promotion'), ('retirement', 'Retirement'), ('other', 'Other Special Event')], max_length=30)),
                ('interest_summary', models.CharField(blank=True, max_length=255)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_gifts', models.ManyToManyField(blank=True, related_name='recommendation_histories', to='gifts.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
