# Generated by Django 5.2.15 on 2026-06-04 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('recipient_type', models.CharField(choices=[('partner', 'Partner'), ('family', 'Family'), ('friend', 'Friend'), ('coworker', 'Coworker')], max_length=30)),
                ('occasion_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('monthsary', 'Monthsary'), ('graduation', 'Graduation'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('valentines', "Valentine's Day"), ('mothers_day', "Mother's Day"), ('fathers_day', "Father's Day"), ('family_reunion', 'Family Reunion'), ('wedding', 'Wedding'), ('baby_shower', 'Baby Shower'), ('promotion', 'Promotion'), ('retirement', 'Retirement'), ('other', 'Other Special Event')], max_length=30)),
                ('minimum_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maximum_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.CharField(blank=True, help_text='Static image path or image URL', max_length=255)),
                ('store_link', models.URLField(blank=True)),
                ('store_name', models.CharField(choices=[('Shopee', 'Shopee'), ('Lazada', 'Lazada'), ('TikTok Shop', 'TikTok Shop'), ('Temu', 'Temu'), ('Other', 'Other')], default='Other', max_length=40)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts', to='gifts.category')),
                ('interests', models.ManyToManyField(blank=True, related_name='gifts', to='gifts.interest')),
            ],
            options={
                'ordering': ['-is_featured', 'price', 'name'],
            },
        ),
    ]
