# Generated by Django 5.2.15 on 2026-06-04 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=160)),
                ('recipient_name', models.CharField(max_length=120)),
                ('occasion_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('monthsary', 'Monthsary'), ('graduation', 'Graduation'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('valentines', "Valentine's Day"), ('mothers_day', "Mother's Day"), ('fathers_day', "Father's Day"), ('family_reunion', 'Family Reunion'), ('wedding', 'Wedding'), ('baby_shower', 'Baby Shower'), ('promotion', 'Promotion'), ('retirement', 'Retirement'), ('other', 'Other Special Event')], max_length=30)),
                ('event_date', models.DateField()),
                ('reminder_days_before', models.PositiveIntegerField(default=7)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('occasion', 'Occasion Reminder'), ('wishlist', 'Wishlist Update'), ('recommendation', 'Gift Suggestion'), ('system', 'System Message')], default='system', max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifts.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('occasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='occasions.occasion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
